/// Flutter icons TransportationIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TransportationIcons
///      fonts:
///       - asset: fonts/TransportationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TransportationIcons {
  TransportationIcons._();

  static const _kFontFam = 'TransportationIcons';
  static const String? _kFontPkg = null;

  static const IconData bus_top_view = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop_4 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop_3 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop_2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
