name: bus_tracker_aw
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^0.14.0
  map_controller: 
    git:
      url: git://github.com/mpinkard/map_controller.git

  appwrite: ^5.0.0
  location: ^4.4.0
  latlong2: ^0.8.1
  url_launcher: ^6.1.2
  sliding_up_panel: ^2.0.0+1
  flutter_switch: ^0.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/cyberjaya-1.geojson
